---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bedtools_slop"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "bedtools":
      ## TODO nf-core: Add a description and other details for the software below
      description: "A powerful toolset for genome arithmetic"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['MIT']
      identifier: biotools:bedtools

## TODO nf-core: Add a description of all of the variables used as input
input:
  #
  ## TODO nf-core: Delete / customise this example input
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          

## TODO nf-core: Add a description of all of the variables used as output
output:
  - bam:
  #
  ## TODO nf-core: Delete / customise this example output
    - "*.bam":
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@apsteinberg"
maintainers:
  - "@apsteinberg"
